title: "Philippe le futur physicien médical / Mon site web personnel"
tit: "Philippe le futur physicien médical"
language_name: "Français"
no_translation: "Désolé, mais cette page n'existe pas en français.<br>Essayez les autres versions:"
not_found: "Désolé, mais la page recherchée semble ne pas exister --- voici une science en compensation."