title: "Philippe der künftige Medizinphysiker / Mein Website"
tit: "Philippe der künftige Medizinphysiker"
language_name: "Deutsch"
no_translation: "Entschuldigung, aber dieses Blatt existiert nicht auf Deutsch.<br>Wahrscheinlich können Sie probieren diese:"
not_found: "Es tut uns leid, aber dieses Blatt existiert nicht --- Wahrscheinlich mögen Sie eine Wissenschaft stattdessen."
not_built: "Dieses Blatt existiert noch nicht, aber wird wharscheinlich sein. Wer weiß!"
