title: "Philippus futurus physicus medicinae / Eius Website"
tit: "Philippus futurus physicus medicinae"
language_name: "Latina"
no_translation: "Pagina non existat lingua latina.<br>Forse est altera lingua:"
not_found: "Sorry, but the page you were trying to view does not exist --- here is a science."