title: "Philippus futurus physicus medicinae / Eius Website"
tit: "Philippus futurus physicus medicinae"
language_name: "Latina"
no_translation: "Pagina non existat lingua latina.<br>Forse est altera lingua:"
not_found: "Hic nulla pagina est --- ecce scientia una."